#ifndef BORN_PROP_ELASTIC_GPU_FUNCTIONS_3D_H
#define BORN_PROP_ELASTIC_GPU_FUNCTIONS_3D_H 1
#include <vector>

/*********************************** Initialization ****************************/
// Gpu info
bool getGpuInfo_3D(std::vector<int> gpuList, int info, int deviceNumber);
void setGpuP2P(int nGpu, int info, std::vector<int> gpuList);
void initBornElasticGpu_3D(float dz, float dx, float dy, int nz, int nx, int ny, int nts, float dts, int sub, int minPad, int blockSize, float alphaCos, int nGpu, int iGpuId, int iGpuAlloc);
void allocateBornElasticGpu_3D(float *rhoxDtw, float *rhoyDtw, float *rhozDtw, float *lamb2MuDt, float *lambDtw, float *muxzDtw, float *muxyDtw, float *muyzDtw, int nx, int ny, int nz, int iGpu, int iGpuId);
void deallocateBornElasticGpu_3D(int iGpu, int iGpuId);
//Functions to allocate and deallocate the pinned-memory wavefield arrays
void allocatePinBornElasticGpu_3D(int nx, int ny, int nz, int nts, int nGpu, int iGpuId, int iGpu, int iGpuAlloc);
void deallocatePinBornElasticGpu_3D(int iGpu, int iGpuId);

/*********************************** Born FWD *********************************/
void BornElasticFwdGpu_3D(float *sourceRegDts_vx, float *sourceRegDts_vy, float *sourceRegDts_vz, float *sourceRegDts_sigmaxx, float *sourceRegDts_sigmayy, float *sourceRegDts_sigmazz, float *sourceRegDts_sigmaxz, float *sourceRegDts_sigmaxy, float *sourceRegDts_sigmayz, float *dataRegDts_vx, float *dataRegDts_vy, float *dataRegDts_vz, float *dataRegDts_sigmaxx, float *dataRegDts_sigmayy, float *dataRegDts_sigmazz, float *dataRegDts_sigmaxz, float *dataRegDts_sigmaxy, float *dataRegDts_sigmayz, long long *sourcesPositionRegCenterGrid, long long nSourcesRegCenterGrid, long long *sourcesPositionRegXGrid, long long nSourcesRegXGrid, long long *sourcesPositionRegYGrid, long long nSourcesRegYGrid, long long *sourcesPositionRegZGrid, long long nSourcesRegZGrid, long long *sourcesPositionRegXZGrid, long long nSourcesRegXZGrid, long long *sourcesPositionRegXYGrid, long long nSourcesRegXYGrid, long long *sourcesPositionRegYZGrid, long long nSourcesRegYZGrid, long long *receiversPositionRegCenterGrid, long long nReceiversRegCenterGrid, long long *receiversPositionRegXGrid, long long nReceiversRegXGrid, long long *receiversPositionRegYGrid, long long nReceiversRegYGrid, long long *receiversPositionRegZGrid, long long nReceiversRegZGrid, long long *receiversPositionRegXZGrid, long long nReceiversRegXZGrid, long long *receiversPositionRegXYGrid, long long nReceiversRegXYGrid, long long *receiversPositionRegYZGrid, long long nReceiversRegYZGrid, float *drhox, float *drhoy, float *drhoz, float *dlame,  float *dmu, float *dmuxz, float *dmuxy, float *dmuyz, int nx, int ny, int nz, int iGpu, int iGpuId);
void BornElasticFwdGpudomDec_3D(float *sourceRegDts_vx, float *sourceRegDts_vy, float *sourceRegDts_vz, float *sourceRegDts_sigmaxx, float *sourceRegDts_sigmayy, float *sourceRegDts_sigmazz, float *sourceRegDts_sigmaxz, float *sourceRegDts_sigmaxy, float *sourceRegDts_sigmayz, float *dataRegDts_vx, float *dataRegDts_vy, float *dataRegDts_vz, float *dataRegDts_sigmaxx, float *dataRegDts_sigmayy, float *dataRegDts_sigmazz, float *dataRegDts_sigmaxz, float *dataRegDts_sigmaxy, float *dataRegDts_sigmayz, long long *sourcesPositionRegCenterGrid, long long nSourcesRegCenterGrid, long long *sourcesPositionRegXGrid, long long nSourcesRegXGrid, long long *sourcesPositionRegYGrid, long long nSourcesRegYGrid, long long *sourcesPositionRegZGrid, long long nSourcesRegZGrid, long long *sourcesPositionRegXZGrid, long long nSourcesRegXZGrid, long long *sourcesPositionRegXYGrid, long long nSourcesRegXYGrid, long long *sourcesPositionRegYZGrid, long long nSourcesRegYZGrid, long long *receiversPositionRegCenterGrid, long long nReceiversRegCenterGrid, long long *receiversPositionRegXGrid, long long nReceiversRegXGrid, long long *receiversPositionRegYGrid, long long nReceiversRegYGrid, long long *receiversPositionRegZGrid, long long nReceiversRegZGrid, long long *receiversPositionRegXZGrid, long long nReceiversRegXZGrid, long long *receiversPositionRegXYGrid, long long nReceiversRegXYGrid, long long *receiversPositionRegYZGrid, long long nReceiversRegYZGrid, float *drhox, float *drhoy, float *drhoz, float *dlame,  float *dmu, float *dmuxz, float *dmuxy, float *dmuyz, int nx, int ny, int nz, std::vector<int> ny_domDec, std::vector<int> gpuList);


/*********************************** Born ADJ *********************************/
void BornElasticAdjGpu_3D(float *sourceRegDts_vx, float *sourceRegDts_vy, float *sourceRegDts_vz, float *sourceRegDts_sigmaxx, float *sourceRegDts_sigmayy, float *sourceRegDts_sigmazz, float *sourceRegDts_sigmaxz, float *sourceRegDts_sigmaxy, float *sourceRegDts_sigmayz, float *dataRegDts_vx, float *dataRegDts_vy, float *dataRegDts_vz, float *dataRegDts_sigmaxx, float *dataRegDts_sigmayy, float *dataRegDts_sigmazz, float *dataRegDts_sigmaxz, float *dataRegDts_sigmaxy, float *dataRegDts_sigmayz, long long *sourcesPositionRegCenterGrid, long long nSourcesRegCenterGrid, long long *sourcesPositionRegXGrid, long long nSourcesRegXGrid, long long *sourcesPositionRegYGrid, long long nSourcesRegYGrid, long long *sourcesPositionRegZGrid, long long nSourcesRegZGrid, long long *sourcesPositionRegXZGrid, long long nSourcesRegXZGrid, long long *sourcesPositionRegXYGrid, long long nSourcesRegXYGrid, long long *sourcesPositionRegYZGrid, long long nSourcesRegYZGrid, long long *receiversPositionRegCenterGrid, long long nReceiversRegCenterGrid, long long *receiversPositionRegXGrid, long long nReceiversRegXGrid, long long *receiversPositionRegYGrid, long long nReceiversRegYGrid, long long *receiversPositionRegZGrid, long long nReceiversRegZGrid, long long *receiversPositionRegXZGrid, long long nReceiversRegXZGrid, long long *receiversPositionRegXYGrid, long long nReceiversRegXYGrid, long long *receiversPositionRegYZGrid, long long nReceiversRegYZGrid, float *drhox, float *drhoy, float *drhoz, float *dlame,  float *dmu, float *dmuxz, float *dmuxy, float *dmuyz, int nx, int ny, int nz, int iGpu, int iGpuId);
void BornElasticAdjGpudomDec_3D(float *sourceRegDts_vx, float *sourceRegDts_vy, float *sourceRegDts_vz, float *sourceRegDts_sigmaxx, float *sourceRegDts_sigmayy, float *sourceRegDts_sigmazz, float *sourceRegDts_sigmaxz, float *sourceRegDts_sigmaxy, float *sourceRegDts_sigmayz, float *dataRegDts_vx, float *dataRegDts_vy, float *dataRegDts_vz, float *dataRegDts_sigmaxx, float *dataRegDts_sigmayy, float *dataRegDts_sigmazz, float *dataRegDts_sigmaxz, float *dataRegDts_sigmaxy, float *dataRegDts_sigmayz, long long *sourcesPositionRegCenterGrid, long long nSourcesRegCenterGrid, long long *sourcesPositionRegXGrid, long long nSourcesRegXGrid, long long *sourcesPositionRegYGrid, long long nSourcesRegYGrid, long long *sourcesPositionRegZGrid, long long nSourcesRegZGrid, long long *sourcesPositionRegXZGrid, long long nSourcesRegXZGrid, long long *sourcesPositionRegXYGrid, long long nSourcesRegXYGrid, long long *sourcesPositionRegYZGrid, long long nSourcesRegYZGrid, long long *receiversPositionRegCenterGrid, long long nReceiversRegCenterGrid, long long *receiversPositionRegXGrid, long long nReceiversRegXGrid, long long *receiversPositionRegYGrid, long long nReceiversRegYGrid, long long *receiversPositionRegZGrid, long long nReceiversRegZGrid, long long *receiversPositionRegXZGrid, long long nReceiversRegXZGrid, long long *receiversPositionRegXYGrid, long long nReceiversRegXYGrid, long long *receiversPositionRegYZGrid, long long nReceiversRegYZGrid, float *drhox, float *drhoy, float *drhoz, float *dlame,  float *dmu, float *dmuxz, float *dmuxy, float *dmuyz, int nx, int ny, int nz, std::vector<int> ny_domDec, std::vector<int> gpuList);

#endif
